export default [
  ['😀', 'Grinning Face'],
  ['😁', 'Beaming Face With Smiling Eyes'],
  ['😂', 'Face With Tears of Joy'],
  ['🤣', 'Rolling on the Floor Laughing'],
  ['😃', 'Grinning Face With Big Eyes'],
  ['😄', 'Grinning Face With Smiling Eyes'],
  ['😅', 'Grinning Face With Sweat'],
  ['😆', 'Grinning Squinting Face'],
  ['😉', 'Winking Face'],
  ['😊', 'Smiling Face With Smiling Eyes'],
  ['😋', 'Face Savoring Food'],
  ['😎', 'Smiling Face With Sunglasses'],
  ['😍', 'Smiling Face With Heart-Eyes'],
  ['😘', 'Face Blowing a Kiss'],
  ['😗', 'Kissing Face'],
  ['😙', 'Kissing Face With Smiling Eyes'],
  ['😚', 'Kissing Face With Closed Eyes'],
  ['☺', 'Smiling Face'],
  ['🙂', 'Slightly Smiling Face'],
  ['🤗', 'Hugging Face'],
  ['🤩', 'Star-Struck'],
  ['🤔', 'Thinking Face'],
  ['🤨', 'Face With Raised Eyebrow'],
  ['😐', 'Neutral Face'],
  ['😑', 'Expressionless Face'],
  ['😶', 'Face Without Mouth'],
  ['🙄', 'Face With Rolling Eyes'],
  ['😏', 'Smirking Face'],
  ['😣', 'Persevering Face'],
  ['😥', 'Sad but Relieved Face'],
  ['😮', 'Face With Open Mouth'],
  ['🤐', 'Zipper-Mouth Face'],
  ['😯', 'Hushed Face'],
  ['😪', 'Sleepy Face'],
  ['😫', 'Tired Face'],
  ['😴', 'Sleeping Face'],
  ['😌', 'Relieved Face'],
  ['😛', 'Face With Tongue'],
  ['😜', 'Winking Face With Tongue'],
  ['😝', 'Squinting Face With Tongue'],
  ['🤤', 'Drooling Face'],
  ['😒', 'Unamused Face'],
  ['😓', 'Downcast Face With Sweat'],
  ['😔', 'Pensive Face'],
  ['😕', 'Confused Face'],
  ['🙃', 'Upside-Down Face'],
  ['🤑', 'Money-Mouth Face'],
  ['😲', 'Astonished Face'],
  ['☹', 'Frowning Face'],
  ['🙁', 'Slightly Frowning Face'],
  ['😖', 'Confounded Face'],
  ['😞', 'Disappointed Face'],
  ['😟', 'Worried Face'],
  ['😤', 'Face With Steam From Nose'],
  ['😢', 'Crying Face'],
  ['😭', 'Loudly Crying Face'],
  ['😦', 'Frowning Face With Open Mouth'],
  ['😧', 'Anguished Face'],
  ['😨', 'Fearful Face'],
  ['😩', 'Weary Face'],
  ['🤯', 'Exploding Head'],
  ['😬', 'Grimacing Face'],
  ['😰', 'Anxious Face With Sweat'],
  ['😱', 'Face Screaming in Fear'],
  ['😳', 'Flushed Face'],
  ['🤪', 'Zany Face'],
  ['😵', 'Dizzy Face'],
  ['😡', 'Pouting Face'],
  ['😠', 'Angry Face'],
  ['🤬', 'Face With Symbols on Mouth'],
  ['😷', 'Face With Medical Mask'],
  ['🤒', 'Face With Thermometer'],
  ['🤕', 'Face With Head-Bandage'],
  ['🤢', 'Nauseated Face'],
  ['🤮', 'Face Vomiting'],
  ['🤧', 'Sneezing Face'],
  ['😇', 'Smiling Face With Halo'],
  ['🤠', 'Cowboy Hat Face'],
  ['🤡', 'Clown Face'],
  ['🤥', 'Lying Face'],
  ['🤫', 'Shushing Face'],
  ['🤭', 'Face With Hand Over Mouth'],
  ['🧐', 'Face With Monocle'],
  ['🤓', 'Nerd Face'],
  ['😈', 'Smiling Face With Horns'],
  ['👿', 'Angry Face With Horns'],
  ['👹', 'Ogre'],
  ['👺', 'Goblin'],
  ['💀', 'Skull'],
  ['👻', 'Ghost'],
  ['👽', 'Alien'],
  ['🤖', 'Robot Face'],
  ['💩', 'Pile of Poo'],
  ['😺', 'Grinning Cat Face'],
  ['😸', 'Grinning Cat Face With Smiling Eyes'],
  ['😹', 'Cat Face With Tears of Joy'],
  ['😻', 'Smiling Cat Face With Heart-Eyes'],
  ['😼', 'Cat Face With Wry Smile'],
  ['😽', 'Kissing Cat Face'],
  ['🙀', 'Weary Cat Face'],
  ['😿', 'Crying Cat Face'],
  ['😾', 'Pouting Cat Face'],
  ['👶', 'Baby'],
  ['👦', 'Boy'],
  ['👧', 'Girl'],
  ['👨', 'Man'],
  ['👩', 'Woman'],
  ['👴', 'Old Man'],
  ['👵', 'Old Woman'],
  ['👮', 'Police Officer'],
  ['🕵', 'Detective'],
  ['💂', 'Guard'],
  ['👷', 'Construction Worker'],
  ['🤴', 'Prince'],
  ['👸', 'Princess'],
  ['👳', 'Person Wearing Turban'],
  ['👲', 'Man With Chinese Cap'],
  ['🧕', 'Woman With Headscarf'],
  ['🧔', 'Man: Beard'],
  ['👱', 'Person: Blond Hair'],
  ['🤵', 'Man in Tuxedo'],
  ['👰', 'Bride With Veil'],
  ['🤰', 'Pregnant Woman'],
  ['🤱', 'Breast-Feeding'],
  ['👼', 'Baby Angel'],
  ['🎅', 'Santa Claus'],
  ['🤶', 'Mrs. Claus'],
  ['🙇', 'Person Bowing'],
  ['🗣', 'Speaking Head'],
  ['👤', 'Bust in Silhouette'],
  ['👥', 'Busts in Silhouette'],
  ['👫', 'Man and Woman Holding Hands'],
  ['👬', 'Two Men Holding Hands'],
  ['👭', 'Two Women Holding Hands'],
  ['💏', 'Kiss'],
  ['👪', 'Family'],
  ['🤳', 'Selfie'],
  ['💪', 'Flexed Biceps'],
  ['👈', 'Backhand Index Pointing Left'],
  ['👉', 'Backhand Index Pointing Right'],
  ['☝', 'Index Pointing Up'],
  ['👆', 'Backhand Index Pointing Up'],
  ['🖕', 'Middle Finger'],
  ['👇', 'Backhand Index Pointing Down'],
  ['✌', 'Victory Hand'],
  ['🤞', 'Crossed Fingers'],
  ['🖖', 'Vulcan Salute'],
  ['🤘', 'Sign of the Horns'],
  ['🖐', 'Hand With Fingers Splayed'],
  ['✋', 'Raised Hand'],
  ['👌', 'OK Hand'],
  ['👍', 'Thumbs Up'],
  ['👎', 'Thumbs Down'],
  ['✊', 'Raised Fist'],
  ['👊', 'Oncoming Fist'],
  ['🤛', 'Left-Facing Fist'],
  ['🤜', 'Right-Facing Fist'],
  ['🤚', 'Raised Back of Hand'],
  ['👋', 'Waving Hand'],
  ['🤟', 'Love-You Gesture'],
  ['✍', 'Writing Hand'],
  ['👏', 'Clapping Hands'],
  ['👐', 'Open Hands'],
  ['🙌', 'Raising Hands'],
  ['🤲', 'Palms Up Together'],
  ['🙏', 'Folded Hands'],
  ['🤝', 'Handshake'],
  ['💅', 'Nail Polish'],
  ['👂', 'Ear'],
  ['👃', 'Nose'],
  ['👣', 'Footprints'],
  ['👀', 'Eyes'],
  ['👁', 'Eye'],
  ['🧠', 'Brain'],
  ['👅', 'Tongue'],
  ['👄', 'Mouth'],
  ['💋', 'Kiss Mark'],
  ['👓', 'Glasses'],
  ['🕶', 'Sunglasses'],
  ['👔', 'Necktie'],
  ['👕', 'T-Shirt'],
  ['👖', 'Jeans'],
  ['🧣', 'Scarf'],
  ['🧤', 'Gloves'],
  ['🧥', 'Coat'],
  ['🧦', 'Socks'],
  ['👗', 'Dress'],
  ['👘', 'Kimono'],
  ['👙', 'Bikini'],
  ['👚', 'Woman’s Clothes'],
  ['👛', 'Purse'],
  ['👜', 'Handbag'],
  ['👝', 'Clutch Bag'],
  ['🎒', 'Backpack'],
  ['👞', 'Man’s Shoe'],
  ['👟', 'Running Shoe'],
  ['👠', 'High-Heeled Shoe'],
  ['👡', 'Woman’s Sandal'],
  ['👢', 'Woman’s Boot'],
  ['👑', 'Crown'],
  ['👒', 'Woman’s Hat'],
  ['🎩', 'Top Hat'],
  ['🎓', 'Graduation Cap'],
  ['🧢', 'Billed Cap'],
  ['⛑', 'Rescue Worker’s Helmet'],
  ['💄', 'Lipstick'],
  ['💍', 'Ring'],
  ['🌂', 'Closed Umbrella'],
  ['☂', 'Umbrella'],
  ['💼', 'Briefcase'],
]